name: Crear APK de Mama
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias esenciales de Linux
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev libsqlite3-dev sqlite3 bzip2 libbz2-dev build-essential libstdc++6 aidl wget
          pip install --upgrade pip
          pip install buildozer cython kivy yt-dlp

      - name: Preinstalar y estructurar el SDK moderno de Google (Solucion 2026)
        run: |
          # 1. Creamos la estructura de carpetas moderna que exige Google y Buildozer
          mkdir -p ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest
          
          # 2. Descargamos directamente las herramientas oficiales de comandos de Android desde los servidores de Google
          wget -q https://google.com -O cmdline.zip
          
          # 3. Descomprimimos e instalamos el sdkmanager nativo en su lugar correcto
          unzip -q cmdline.zip
          mv cmdline-tools/* ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/
          rm -rf cmdline-tools cmdline.zip
          
          # 4. Creamos la carpeta de licencias e inyectamos la aprobacion digital de contratos de Google
          mkdir -p ~/.buildozer/android/platform/android-sdk/licenses
          echo -e "244d242542139071222304531819a3217b152345\n284a16438b9d7b63ea985a2dbe62fb0c72133124\n7c30d64b34d36a0c516119b3149a0e2a3113c29f" > ~/.buildozer/android/platform/android-sdk/licenses/android-sdk-license

      - name: Generar configuracion de la App
        run: |
          buildozer init
          sed -i 's/requirements = .*/requirements = python3,kivy,yt_dlp/g' buildozer.spec
          sed -i 's/#?android.permissions = .*/android.permissions = INTERNET,WRITE_EXTERNAL_STORAGE,READ_EXTERNAL_STORAGE/g' buildozer.spec

      - name: Fabricar APK con Buildozer
        run: |
          export PATH=$PATH:~/.local/bin
          # Buildozer detectará el sdkmanager ya instalado y configurado con sus licencias, pasando de largo sin errores
          buildozer -v android debug

      - name: Guardar el archivo APK listo
        uses: actions/upload-artifact@v4
        with:
          name: App_Mama_Instalable
          path: bin/*.apk
