name: Crear APK de Mama
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias del sistema y AIDL global
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev libsqlite3-dev sqlite3 bzip2 libbz2-dev build-essential libstdc++6 aidl
          pip install --upgrade pip
          pip install buildozer cython kivy yt-dlp

      - name: Generar configuracion limpia
        run: |
          buildozer init
          sed -i 's/requirements = .*/requirements = python3,kivy,yt_dlp/g' buildozer.spec
          sed -i 's/#?android.permissions = .*/android.permissions = INTERNET,WRITE_EXTERNAL_STORAGE,READ_EXTERNAL_STORAGE/g' buildozer.spec

      - name: Preparar entorno Android sin comandos rotos
        run: |
          # 1. Creamos la carpeta donde Buildozer descargará el SDK
          mkdir -p ~/.buildozer/android/platform/android-sdk/licenses
          
          # 2. Inyectamos la firma digital de la licencia de Google de forma directa y manual
          # Esto hace que Android apruebe los contratos al instante sin usar el comando 'licenses' que da error
          echo -e "244d242542139071222304531819a3217b152345\n284a16438b9d7b63ea985a2dbe62fb0c72133124\n7c30d64b34d36a0c516119b3149a0e2a3113c29f" > ~/.buildozer/android/platform/android-sdk/licenses/android-sdk-license

      - name: Fabricar APK con Buildozer
        run: |
          export PATH=$PATH:~/.local/bin
          # Ejecuta la compilación limpia. Aceptará los términos automáticamente gracias al archivo de arriba.
          buildozer -v android debug

      - name: Guardar el archivo APK listo
        uses: actions/upload-artifact@v4
        with:
          name: App_Mama_Instalable
          path: bin/*.apk
